// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntjgxetzkllnyzkvhiss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50amd4ZXR6a2xsbnl6a3ZoaXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1OTY2NDQsImV4cCI6MjA3MzE3MjY0NH0.J2a5kI1_EnkLk-i0BZqpU89FSWurQ1mCdzaUxwPZLDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});